### PR TITLE
Fix library files inconsistencies

### LINKED ISSUE #2686: [Bug]: Recurring crash
### Describe the issue

I'm not really sure what else I can add except these two things from the log. 

- The file that errors is an epub.
- There seem to be square brackets in the path to the file. 
- There is no such file or directory on my server, hasn't been for a while. 
- I split up my collection into different libraries, but then that didn't really work out (listening data was lost) so I now have three extra libraries pointing to subfolders, and my main library points to the folder above, so the libraries share some content. I never open the extra libraries.

_Here's the log, the crash is in bold:_ 

2024-02-28 12:53:39.090

INFO

=== Starting Server ===

2024-02-28 12:53:39.091

INFO

[Server] Init v2.8.0

2024-02-28 12:53:39.104

INFO

[Database] Initializing db at "/config/absdatabase.sqlite"

2024-02-28 12:53:39.183

INFO

[Database] Db connection was successful

2024-02-28 12:53:39.379

INFO

[Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting, customMetadataProvider

2024-02-28 12:53:40.117

WARN

Removed 1 sessions that were 3 seconds or less

2024-02-28 12:53:40.124

INFO

[LogManager] Removed daily log: 2024-02-21.txt

2024-02-28 12:53:40.125

INFO

[LogManager] Init current daily log filename: 2024-02-28.txt

2024-02-28 12:53:40.222

INFO

[BackupManager] 0 Backups Found

2024-02-28 12:53:40.223

INFO

[BackupManager] Auto Backups are disabled

2024-02-28 12:53:40.248

INFO

[Watcher] Initializing watcher for "Fiction".

2024-02-28 12:53:40.251

INFO

[Watcher] Initializing watcher for "Podcasts".

2024-02-28 12:53:40.252

INFO

[Watcher] Initializing watcher for "Comedy".

2024-02-28 12:53:40.252

INFO

[Watcher] Initializing watcher for "non-fiction".

2024-02-28 12:53:40.252

INFO

[Watcher] Initializing watcher for "History & Biography".

2024-02-28 12:53:40.265

INFO

Listening on port :80

2024-02-28 12:53:40.381

INFO

[Watcher] "Podcasts" Ready

2024-02-28 12:53:40.770

INFO

[Watcher] "Comedy" Ready

2024-02-28 12:53:40.940

INFO

[Watcher] "non-fiction" Ready

2024-02-28 12:53:40.981

INFO

[Watcher] "History & Biography" Ready

2024-02-28 12:53:42.313

INFO

[Watcher] "Fiction" Ready

2024-02-28 13:00:00.649

INFO

[LibraryScanner] Library metadata precedence changed since last scan. From [folderStructure,audioMetatags,txtFiles,opfFile,absMetadata] to [audioMetatags,txtFiles,opfFile,absMetadata,folderStructure]

2024-02-28 13:00:00.651

INFO

[LibraryScanner] Starting (forced) library scan 05246d51-dacf-4a88-aafd-9b90c897b4de for Fiction

**2024-02-28 13:00:20.746**

**ERROR**

**[parseEpubMetadata] Failed to extract META-INF/container.xml from epub at "/audiobooks/Author Name/Redacted The Step By Step Guide To Redacted by Works, Companion [Works, Companion]/Redacted The Step By Step Guide To Redacted by Works, Companion [Works, Companion].epub" Error: ENOENT: no such file or directory, open '/audiobooks/Author Name/Redacted The Step By Step Guide To Redacted by Works, Companion [Works, Companion]/Redacted The Step By Step Guide To Redacted by Works, Companion [Works, Companion].epub'**

**2024-02-28 13:00:20.749**

**FATAL**

**[Server] Unhandled rejection: Error: ENOENT: no such file or directory, open '/audiobooks/Author Name/Redacted The Step By Step Guide To Redacted by Works, Companion [Works, Companion]/Redacted The Step By Step Guide To Redacted by Works, Companion [Works, Companion].epub', promise: Promise { <rejected> [Error: ENOENT: no such file or directory, open '/audiobooks/Author Name/Redacted The Step By Step Guide To Redacted by Works, Companion [Works, Companion]/Redacted The Step By Step Guide To Redacted by Works, Companion [Works, Companion].epub'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/audiobooks/Author Name/Redacted The Step By Step Guide To Redacted by Works, Companion [Works, Companion]/Redacted The Step By Step Guide To Redacted by Works, Companion [Works, Companion].epub' } }**

### Steps to reproduce the issue

I'm not interacting with app or server when this happens. Or I don't think I am? I may have opened the app at those times? Will add to this if that turns out to be the case. 

### Audiobookshelf version

v2.8.0

### How are you running audiobookshelf?

Docker

### PR DESCRIPTION
**Pull request by mikiher**
Fixes #2686 

After some further investigation, it looks like the code already covers Audio files media updates for modified files, so what I ended up doing was the following:
- Refactored library files properties in LibraryItemScanData
- Used the refactored properties above in BookScanner and PodcastScanner to update media with modified ebook/cover library files
- Fixed another related bug in which libraryFolderId in LibraryItem was also not properly updated when books were moved between different library folders within the same library

To test this, I did a lot of moving of directries between different folders (with audio/ebooks/covers) in the same library ) with watcher on and off (and running library scans when watcher was off). Now everything seems to be working without crashes or errors, and the database records look fine after each move. I'd like to write unit tests, but the code is so complicated that I need to wrap my head around how to do it properly.

Also, I still need to write a db migration script to fix existing corrup records, but I think it's important to check in the logic fixes first because of the nasty crashes and corruptions the current code can potentially create.

### CODE REVIEW

**Comment by mikiher** [comment]
I also added a fix to #2767, since it touches the same areas of code.

In a nutshell, I fixed the library item matching logic, in both the watcher and the library scan code paths.

Up until now, it was only able to find an existing library item if it had the same ino as the detected change. 
This logic missed moving of files from the root folder to a sub folder and vice versa (because in those moves, the library item ino changes from file ino to folder ino, or the other way round), which caused #2767.

I changed the logic to also match between an item's ino and the other item's library file inos (and the other way round).

Again, I tested this extensively trying to move an audio file around, with watcher disabled and library scans, and with watcher enabled. This seems to work well now.

**Comment by mikiher** [comment]
Just a couple of meta comments on all of this:
- I find the code for handling file updates to be extremely complex and brittle. I think we really need to think of ways to simplify it.
- The scanLibrary and scanFolderUpdates code paths should be doing roughly the same thing, and yet they are very different and share too little code. I understand the need for different approaches because of the different latency and performance constraints, but we should really strive to make them share as much code as possible.

**Comment by advplyr** [comment]
The functions that are grouping files into library item paths is something I've wanted to refactor for a while so they can share the same function.

File: server/scanner/LibraryScanner.js [hunk 1]
```diff
@@ -603,3 +617,55 @@ function hasAudioFiles(fileUpdateGroup, itemDir) {
...
+  const existingLibraryItem = await Database.libraryItemModel.findOneOld([
+    {
+      libraryId: libraryId
+    },
+    sequelize.where(sequelize.literal('(SELECT count(*) FROM json_each(libraryFiles) WHERE json_valid(json_each.value) AND json_each.value->>"$.ino" = :inode)'), {
+      [sequelize.Op.gt]: 0
+    })
+  ], {
+    inode: ino
+  })
```
Comment (advplyr) [inline server/scanner/LibraryScanner.js:647]: Some file systems have inode values that are only a few digits long so I added this additional query that uses sqlite json functions. Unfortunately this is an extra query and is sqlite specific but in Sequelize v7 they are adding support for handling JSON queries.

**Comment by advplyr** [comment]
I tested a lot of situations and it is working for all the cases you solved for. I found an existing bug with the scanner that I overlooked when I switched everything to sqlite.

The bug can be reproduced by..
1. Create a new book by putting an audio file in `/Test Author/Test Book/audiofile.mp3`
2. Once book is scanned in move audiofile.mp3 to `/Test Author/audiofile.mp3`
3. Note scanner ignores the update with
```[2024-03-23 14:53:10.596] WARN: [LibraryScanner] Files were modified in a parent directory of a library item "/audiobooks/Test Author/Test Title" - ignoring (LibraryScanner.js:583)```

I'm not sure how to solve for that yet. This logic is getting complex as you mentioned.
There is another issue of starting the audiofile.mp3 in one folder and moving it to a subfolder. The library item folder will remain the original folder so adding other files in there will be considered the same book.

**Comment by mikiher** [comment]
Regarding the bug, I looked at this "first pass" code, and I must admit I don't have clear understanding of what this code is supposed to do, and why... the comment doesn't really help. I'll try to read it more carefully, but if you have a moment, I'd appreciate a short exaplanation.

**Comment by advplyr** [comment]
Yeah this is a mess just looking at it again. I'll take a stab at cleaning up that function

**Comment by iconoclasthero** [comment]
+1
